server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      default-filters:
        # Dedupe any duplicate CORS headers just in case (downstream should not set them)
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
      routes:
        # Performance Service
        - id: performance-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/performance/**
          
        
        # Messaging Service (removed)
          
        
        # Admin Request Service
        - id: admin-request-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/admin-requests/**
          
        
        # Medical Service
        - id: medical-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/medical/**
          
        
        # Finance Service
        - id: finance-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/finance/**
          
        
        # Auth Service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          
        
        # Planning Service
        - id: planning-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/planning/**

        # Chatbot Gateway
        - id: chatbot-gateway
          uri: http://localhost:8082
          predicates:
            - Path=/api/chatbot/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
            allowCredentials: true

  endpoint:
    health:
      show-details: always

 

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
