server:
  port: 8082

spring:
  application:
    name: chatbot-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

api:
  groq:
    url: https://api.groq.com/openai/v1/chat/completions
    key: ${GROQ_API_KEY}

services:
  performance:
    base-url: http://localhost:8083

logging:
  level:
    org.apache.fontbox.ttf: error
    org.apache.pdfbox: warn

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/